apiVersion: v1
kind: Pod

metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    environment: development
spec:
  containers:
  - name: frontend
    image: nginx
        