apiVersion: v1
kind: Pod
metadata:
  name: annotations
  namespace: roboshop
  labels:
    project: roboshop
    environment: development
  annotations:
    jenkins.url: http://jenkins.mycompany.internal:8080 
    imageregistry: http://hub.docker.com


spec:
  containers:
  - name: nginx
    image: nginx
        