apiVersion: v1
kind: Pod
metadata:
  name: resources
  namespace: roboshop
  labels:
    project: roboshop
    environment: development
  annotaions:
    imageregistry: http://hub.docker.com

spec:
  containers:
  - name: resources
    image: nginx
    resources:
      requests:
        memory: "80Mi"
        cpu: "100m"
      limits:
        memory: "120Mi"
        cpu: "150m"
          

