apiVersion: v1
kind: Pod
metadata:
  name: env
  namespace: roboshop
  labels:
    project: roboshop
  annotations:
    imageregistry: http//hub.docker.com
spec:
  containers:
  - name: env
    image: nginx
    env:
    - name: course
      value: k8
    - name: demo-project
      value: roboshop
        
      
