apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    environment: dev
    component: frontend
  ports:
    - protocal: TCP
      port: 80 # service port or load balancer port we requests comes with this port to the service or LB
      targetport: 80 # container port or pod port
      

