apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: roboshop
spec:
  type: LoadBalancer

  selector:
    project: roboshop
    environment: dev
    component: frontend
    purpose: load-balancer

  ports:
    - protocol: TCP
      port: 80 # traffic goes to clusterip using port 80 and port is the service-facing port on the ClusterIP,
      targetPort: 80 #Forward traffic to port 80 inside the container and the container port where the application is actually listening